#全局配置
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

jasypt:
  encryptor:
    password: YiboYun

webapp:
  name: 医博基础技术框架V1.2.5
  swagger-open: true
  token-save-redis: false # token是否存储在redis上
  token-expire-time: 60   # token过期时间（分钟）
  save-login-time: 7      # 用户选择保存登录状态对应token过期时间（天）
  login-time-limit: 5     # 限制用户登陆错误次数（次）
  login-after-time: 10    # 错误超过次数后多少分钟后才能继续登录（分钟）
  #日志记录相关
  log:
    enabled: true
    addPathPatterns:
      - /**
    excludePathPatterns:
      - /api/log/*
      - /common/**
      - /druid/**
      - /error

#Srping相关配置
spring:
  profiles:
    active: @spring.active@

  #Redis配置
  redis:
      host: 192.168.1.244
      port: 8379
      password: ENC(108NCrFBdhsxAwdjy36x4g==)

  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    #Druid配置
    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall,log4j
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 过滤器配置
      filter:
        wall:
          enabled: true
          config:
            none-base-statement-allow: true
            multi-statement-allow: true
      # 监控配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: root
        login-password: ENC(FO2oLd1xhXRyjIFkhaBwR+LXBOXFHAjH)
        allow: # IP白名单
        deny:  # IP黑名单

#Mybatis配置
mybatis:
  #指定sql映射文件位置
  mapper-locations: classpath*:com/yibo/modules/**/mapping/*.xml
  #配置信息
  configuration:
    map-underscore-to-camel-case: true

#忽略鉴权url
ignored:
  urls:
    - /common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /webjars/springfox-swagger-ui/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico

#Swagger界面内容配置
swagger:
  title: Yiboweb API接口文档
  description: Yiboweb Api Documentation
  version: 1.0.0
  terms-service-url: http://www.gz-yibo.com/
  contact:
    name: YiboYun
    url: http://www.gz-yibo.com/
    email: gogo163gao@163.com

---

#本地环境
spring:
  profiles: local
  datasource:
    username: root
    password: ENC(WZH8zMOp2pSR7kxfp2LQsw==)
    url: jdbc:mysql://localhost:3306/yibo_frame?allowMultiQueries=true

---

#开发环境
spring:
  profiles: dev
  datasource:
    username: root
    password: ENC(tzolKZvgH0mCwcJQPN5vtA==)
    url: jdbc:mysql://192.168.1.244:3036/yibo_frame?allowMultiQueries=true

---

#测试环境
spring:
  profiles: test
  datasource:
    username: root
    password: ENC(4E7U6IcbrPePfppGqDWalA==)
    url: jdbc:mysql://192.168.1.244:3036/yibo_frame?allowMultiQueries=true

---

#生产环境
spring:
  profiles: produce
  datasource:
    username: root
    password: ENC(4Q4ABgmCB71R6ConFllkIQ==)
    url: jdbc:mysql://192.168.1.244:3036/yibo_frame?allowMultiQueries=true